# Generated by Django 3.1.3 on 2020-11-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='kit',
            field=models.CharField(blank=True, max_length=4, verbose_name='используемый набор'),
        ),
    ]
